version: '3.9'

services:
  server:
    build: ./server
    container_name: chat_server
    ports:
      - "8000:8000"
    restart: always

  client:
    build: ./client
    container_name: chat_client
    ports:
      - "5173:5173"
    depends_on:
      - server
    restart: always
